import "../globals.css";

export const metadata = {
  title: "SaaS || Interface ",
  description: "Generated by muhamash",
};

export default async function InterfaceLayout({children}) {
  return (
    <>
      { children }
    </>
  )
}