import "../globals.css";

export const metadata = {
  title: "SaaS || Admin",
  description: "Generated by muhamash",
};

export default async function DashboardLayout({children}) {
  return (
    <>
      { children }
    </>
  )
}
